/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ımageeffect;

import javax.swing.JCheckBox;

/**
 *
 * @author acer
 */
public class ButtonPanel extends javax.swing.JPanel {
    ImagePanel ip;
    MainFrame fr = null;
    /**
     * Creates new form ButtonPanel
     */
    public ButtonPanel() {
        initComponents();
    }
    public void setIP(ImagePanel ip){
        
        this.ip=ip;
    }
    public void setFR(MainFrame fr){
    
        this.fr=fr;
        
    }
    public boolean getEffect1() {
        return effect1.isSelected();
    }
    public boolean getEffect2() {
        return effect2.isSelected();
    }
    public boolean getEffect3() {
        return effect3.isSelected();
    }
    public boolean getEffect4() {
        return effect4.isSelected();
    }
    public boolean getEffect5() {
        return effect5.isSelected();
    }
    public boolean getEffect6() {
        return effect6.isSelected();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        effect1 = new javax.swing.JCheckBox();
        effect2 = new javax.swing.JCheckBox();
        effect3 = new javax.swing.JCheckBox();
        effect4 = new javax.swing.JCheckBox();
        effect5 = new javax.swing.JCheckBox();
        effect6 = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        brightness = new javax.swing.JSlider();
        redValue = new javax.swing.JSlider();
        greenValue = new javax.swing.JSlider();
        blueValue = new javax.swing.JSlider();
        colorValue = new javax.swing.JSlider();

        setMaximumSize(new java.awt.Dimension(200, 1200));
        setMinimumSize(new java.awt.Dimension(150, 100));
        setPreferredSize(new java.awt.Dimension(180, 600));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(265, 33));

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(saveButton);

        add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setMinimumSize(new java.awt.Dimension(700, 59));

        jSeparator1.setPreferredSize(new java.awt.Dimension(150, 0));
        jPanel2.add(jSeparator1);

        effect1.setText("Channels Swap");
        effect1.setPreferredSize(new java.awt.Dimension(130, 23));
        effect1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                effect1İtemStateChanged(evt);
            }
        });
        jPanel2.add(effect1);

        effect2.setText("jCheckBox2");
        effect2.setPreferredSize(new java.awt.Dimension(130, 23));
        effect2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                effect2İtemStateChanged(evt);
            }
        });
        jPanel2.add(effect2);

        effect3.setText("Manachrom");
        effect3.setPreferredSize(new java.awt.Dimension(130, 23));
        effect3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                effect3İtemStateChanged(evt);
            }
        });
        jPanel2.add(effect3);

        effect4.setText("jCheckBox4");
        effect4.setPreferredSize(new java.awt.Dimension(130, 23));
        effect4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                effect4İtemStateChanged(evt);
            }
        });
        jPanel2.add(effect4);

        effect5.setText("jCheckBox5");
        effect5.setPreferredSize(new java.awt.Dimension(130, 23));
        effect5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                effect5İtemStateChanged(evt);
            }
        });
        jPanel2.add(effect5);

        effect6.setText("Invert");
        effect6.setPreferredSize(new java.awt.Dimension(130, 23));
        effect6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                effect6İtemStateChanged(evt);
            }
        });
        jPanel2.add(effect6);

        jSeparator2.setPreferredSize(new java.awt.Dimension(150, 70));
        jPanel2.add(jSeparator2);

        brightness.setMaximum(50);
        brightness.setMinimum(-50);
        brightness.setValue(0);
        brightness.setBorder(javax.swing.BorderFactory.createTitledBorder("Brightness"));
        brightness.setPreferredSize(new java.awt.Dimension(150, 49));
        brightness.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                brightnessStateChanged(evt);
            }
        });
        jPanel2.add(brightness);

        redValue.setMaximum(50);
        redValue.setMinimum(-50);
        redValue.setValue(0);
        redValue.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RED", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0))); // NOI18N
        redValue.setPreferredSize(new java.awt.Dimension(150, 49));
        redValue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                redValueStateChanged(evt);
            }
        });
        jPanel2.add(redValue);

        greenValue.setMaximum(50);
        greenValue.setMinimum(-50);
        greenValue.setValue(0);
        greenValue.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GREEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 255, 0))); // NOI18N
        greenValue.setPreferredSize(new java.awt.Dimension(150, 49));
        greenValue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                greenValueStateChanged(evt);
            }
        });
        jPanel2.add(greenValue);

        blueValue.setMaximum(50);
        blueValue.setMinimum(-50);
        blueValue.setValue(0);
        blueValue.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BLUE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N
        blueValue.setPreferredSize(new java.awt.Dimension(150, 49));
        blueValue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                blueValueStateChanged(evt);
            }
        });
        jPanel2.add(blueValue);

        colorValue.setMaximum(50);
        colorValue.setMinimum(-50);
        colorValue.setValue(0);
        colorValue.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "COLOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 0, 102))); // NOI18N
        colorValue.setPreferredSize(new java.awt.Dimension(150, 49));
        colorValue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                colorValueStateChanged(evt);
            }
        });
        jPanel2.add(colorValue);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void effect1İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_effect1İtemStateChanged
        ip.repaint();
    }//GEN-LAST:event_effect1İtemStateChanged

    private void effect2İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_effect2İtemStateChanged
        ip.repaint();
    }//GEN-LAST:event_effect2İtemStateChanged

    private void effect3İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_effect3İtemStateChanged
        ip.repaint();
    }//GEN-LAST:event_effect3İtemStateChanged

    private void effect4İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_effect4İtemStateChanged
        ip.repaint();
    }//GEN-LAST:event_effect4İtemStateChanged

    private void effect5İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_effect5İtemStateChanged
        ip.repaint();
    }//GEN-LAST:event_effect5İtemStateChanged

    private void effect6İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_effect6İtemStateChanged
        ip.repaint();
    }//GEN-LAST:event_effect6İtemStateChanged

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        effect1.setSelected(false);
        effect2.setSelected(false);
        effect3.setSelected(false);
        effect4.setSelected(false);
        effect5.setSelected(false);
        effect6.setSelected(false);
        brightness.setValue(0);
        redValue.setValue(0);
        greenValue.setValue(0);
        blueValue.setValue(0);
        colorValue.setValue(0);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        fr.save();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void brightnessStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_brightnessStateChanged
        ip.setBrightness(brightness.getValue());
        ip.repaint();
    }//GEN-LAST:event_brightnessStateChanged

    private void redValueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_redValueStateChanged
        ip.setRed(redValue.getValue());
        ip.repaint();
    }//GEN-LAST:event_redValueStateChanged

    private void greenValueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_greenValueStateChanged
        ip.setGreen(greenValue.getValue());
        ip.repaint();
    }//GEN-LAST:event_greenValueStateChanged

    private void blueValueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_blueValueStateChanged
       ip.setBlue(blueValue.getValue());
       ip.repaint();
    }//GEN-LAST:event_blueValueStateChanged

    private void colorValueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_colorValueStateChanged
        ip.setColor(colorValue.getValue());
        ip.repaint();
    }//GEN-LAST:event_colorValueStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider blueValue;
    private javax.swing.JSlider brightness;
    private javax.swing.JButton cancelButton;
    private javax.swing.JSlider colorValue;
    private javax.swing.JCheckBox effect1;
    private javax.swing.JCheckBox effect2;
    private javax.swing.JCheckBox effect3;
    private javax.swing.JCheckBox effect4;
    private javax.swing.JCheckBox effect5;
    private javax.swing.JCheckBox effect6;
    private javax.swing.JSlider greenValue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSlider redValue;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
